def remove_duplicate_lines_to_file(input_text: str, output_file: str):
    seen = set()
    unique_lines = []
    duplicates = []

    for line in input_text.splitlines():
        line = line.strip()
        if line in seen:
            duplicates.append(line)
        else:
            seen.add(line)
            unique_lines.append(line)

    # Write unique names to file
    with open(output_file, 'w') as f:
        f.write('\n'.join(unique_lines))

    # Print removed duplicates
    if duplicates:
        print("Removed duplicate names:")
        for name in duplicates:
            print(f"- {name}")
    else:
        print("No duplicates found.")

# --- Example usage ---
if __name__ == "__main__":
    sample_input = """Sullivan, Colin
Savell, Quinn
Shrimanker, Amee
Horvat, Jacob
Lee, Ning
Fetter, Lauren
Currier, Taylor
Peeler, Grace
Bedol, Lacy
Rubenstein, Alec
Patel, Minesh
Blazevich, Christie
Carr, Emily
Cherry, Edward
Sundaram, Shruthi
Biernacki, Claire
Lee, April
Zhu, Mingjun
Morales, Sofia
Farley, Clark
Hetzel, Jessica
schmidt, sondra
Lee, Vivian
Stevenson, Benjamin
Bukovac, Eric
Powers, Caitlin
Foster, Brandon
Marshall, Elisa
Pardue, Taylor
Rowsey, Kevin
Dunlevie, Scott 
Siphers, Amy
Jongkind, Kara
Falduti, Briana
Engel, Heather
Ni, Yukai
Levy, Matthew
Ruark, Jocelyn
Fisher, Andrew
Shaw, Austin
Casscells-Hamby, Stephen
Bradshaw, Lucie
Hodges, Joseph
Goodwin, Zane
Huang, Sunny
Pitcavage, Ryann
Fagan, Carolyn
wu, xiangying
Gott, Caroline
Babbitt, Alex
Bailey, Paul
Almeter, Alexandra
Boland, Robert
Green, Dylan
Hulme, David
Mavromatis, Lucas
Bisarya, Rashi
Harrill, Abby
Brews, Kristen
Meer, Jordan
Bench, Tyler
Rowell, Kathryn
Thomas, Mackenzie
Dzera, John
Annen, Brian
Isabel, Thomas
Carr, Christopher
Benson, Shelby
Gage, Charles
Marquez, Gabriela
Buoyer, Elizabeth
Chapman, Connor
Ludlow, Nicholas
Cooney, Devin
Peterson, Brandon
Wilson, Rufus
Ji, Kevin
Hoppe, Steven
Mo, Chenming
McTier, Thomas
De Bruycker, Zoe
Partain, Jack
Dunn, Jason
Rao, Kalyan
Shuford, Benjamin
Howard, Katie
Low, Thomas
McCormick, William
Sarnoff, Zach
Oddo, Sarah
Quinones, Brandon
Gibson, Erin
Morgan, John
Sisk, Tate
Garcia, Alfredo
Ramanan, Niyama
Hartsfield, Raven
Porter, Chanel
Peele, Lindsay
Hubert, Marshall
Patel, Leena
Collins, Stephen
Roper, Burke
Zheng, Charles
Johnson, Thomas
Morgenstern, Daniel
Caton, Kyle
McArthur, Peter
Lewis, Andrew
Langer, Stefan
Thomas, Kaitlyn
Velten, Sarah
Thaden, Michael
Nealon, Robert
Williford, Ira
Iannone, Marie
Rossello, Jorge
Taylor, Paul
Wilkison, Mary
Patton, Steven
Duncan, Emily
Mendu, Sarika
Neville, Kacie
Gil, Vanessa
Cooper, Matthew
Richard, Brandon
Williams, Rachel
Daughtridge, Andrew
Carmenate, Joshua 
Verdi, Anna
Schilling, Kayla
Childress, John
Weiss, Marissa
Tan, Gabriel 
Daniels, Jonathan
Porter, Ellen
Dinkins, Michael
Silva, Christopher
Aldana, Victoria
Meza, Priscila
Schapira, Benjamin
Aldridge, John
McArthur, Samuel
Torp, Sarah
Anastas-King, Grant
Mook, Robert
Haba, Daniel
Hurwitz, Austin
Darvin, Andrew
Kosmala, Emily
Schwartz, Amy
Grabbe, Nicholas
Schroeder, Cyrus
Chudasama, Shalini
Huber, Sean
Nally, Brendan
Patel, Beejal
Pureco, Hector
Mangrum, Kailyn
Lainez, Christie
Travis, Charles
Wu, Huihui
Maniloff, Zachary
Harrison, Noni
Taverna, GianMarco
Sachdev, Nishant
Crawford, Corey
Carroll, Robert
Davis, Jamal
Trifari, Ethan
Peterson, Hannah
Newell, Nathaniel
Zlatev, Zachary
Fisher, Audrey
Purohit, Priyank
Thorne, Elizabeth
Schneider, Mark
Lindley, Caroline
Cho, Jasmine
Stang, Noah
Rowe, Erin
DePopas, Kevin
Keil, Erika
Lakhwani, Rahul
Rodriguez, Carlos
Onsager, Marissa
Warren, Daniel
Rodriguez, Jacquelyn
Brown, Rachel
Kennihan, Mary
Furlong, James
Xiong, Jessica
Padgett, Joseph
Nard, Kevin
Apollon, Dominique
Baqai, Minhaj
Veazey, Andrew
Brown, Casey
Thompson, Emily
Desberg, Sara
Kearby, Daniel
Procaccini, Ryan
Swami, Shyamal
Magjuka, Meredith
Rusk, Katherine
Seitzer, Tricia
Cardwell, Katherine
Saunders, Ben
Pope, Rusher
Duemichen, Andreas
Patidar, Sheev
Jones, Robert
Caudle, John
Lampley, Kevin
Cohen, Mary
Strickman, Emily
Morrison, Timothy
Conger, Jacob
McCaul, Mack
Meffert, Adam 
Barber, Margaret
Carrera, Frances
Smith, Elise
Hermanson, Michael
Keeter, Addie
Morse, Jennifer
Harris, Breanna
Kritz, Hilary
Muse, Matthew
Ravenscraft, Lance
Kupres, Steven
Ikoma, Michelle
Traywick, Franklin
Ramadan, Kareem
Uquillas, Daniel
Ramsay, George
Curulla, Matthew
Lewis, Brandon
Kenna, Patrick
Uffelman, Julie
Fleming, Alexander
Saunders, Sabrina
Wages, Dawn
Humann, Nicholas
DeBolt, Catherine
Ferebee, Mary Kathryn 
Noblin, Jillian
Patel, Neal
Salvia, Megan
Farrell, Conner
FLESHER, CHRISTOPHER
Gandhi, Parth
Wu, Frank
Brenner, Nicholas
Cockerham, Trevor
Cope, Kristen
Eugenio, Isa
Shah, Sonia
Chai, Jen
Mason, John
Safrit, Grace
Bojanski, Michael
Gaylor, John Paul
Hurley, Matt
Moroney, Julie
Wolberg, Carly
Kenney, Scott
McClintock, Brian
Pappas, John
Frere, Olivia
Brandt, Eric
Wu, Wen
Peters, Katherine
Peterson, Kara
Russell, Sawyer
Schindler, Blake
Stone, Sam
Wallace, Tyler
Zaleon, Beth
Teal, Bryant
Horrigan, Olivia
Patel, Jay
Santanam, Sachin
Gratto, Nick
McAnallen, Ryan
Tate, Meredith
Wasser, Max
Zittel, George
Spurr, Sarah
Poole, Sam
Glock, Ben
Kataja, Darren
Prieto, David
Lombardi, Vincent
Bowser, Ashley
Klein, Alex
Zhao, Ben
Brown, Robert
Crutchfield, Elisa
Rothstein, Matthew
Powell, Eric
Dickinson, Jack
Whitcomb, Luke
Yin, Bo
Starnes, Cameron
Mangum, Kristen
Sawchak, Benjamin
DeBlock, John
Level, Joseph
Wintermeir, Daniel
Michael, Stephanie
Register, Robert
Foster, Justin
Arnal Prieto, Paulina 
Shahbazi, Soroush
Hai, Kimi
Richey, Daniel
Sutton, Grant
Zhou, Angela
Gallagher, Brendon
Furr, Chase
Zhu, Violette
Benkert, Evan
Deal, Brad
Lesser, Ellen
Piasecki, Alexander
Wood, Andrew
Wood, Andrew 
Chang, May
Salito, Hailey
Wang, Zihan
Agnew, Pendleton
Arnie, Samuel
Deal, Stephen
McClain, Alexa
Whitcomb, Mike
Wu, Ziyou
Nations, Andrew
Loeb, Alec
Smith, Erin
Kinsey, Bryan
Weidman, Will
Karas, Scott
Caldwell, Lauren
Becker, Maegan
Powell, Austin
Satsangi, Parag
Sekhon, Gurjant
Steiner, Alexander
McDonagh, Chris
Wildeman, Kelcie
Hanson, Laura
Sherwood, Landon 
Brandes, Joey
Busby, Kristen
Pezza, Cassandra 
Lamberton, Lincoln
Reynolds, Erika
Schmith, Angela
Brown, Jennifer
Hamilton, Kenneth
Hill, Brooke
Glover, Joshua
Jacobson, Sophie
Dull, William
Pritchard, Peter
Schmelzle, Megan 
Obi-Gwacham, CeeCee
Belson, Connor
Harakas, Demetri
Chaves, Andrea
Holtman, Kyle
Behar, Rebecca
Abbondanza, Frank
Zheng, Richard
Nicholson, Robert
Devine, Alexandra
Hilliard, Sophia
Abood, Dahnoun
Talebi, Kristian
Ruffin, Emily
Wertz, Katrina
Xu, Aimee
Rolison, Devon
Bermingham, Ciaran
Biyyala, Dushyanth
Dewberry, Donald
Haga, Trevor
Galdi, Joseph
Reasons, Devin
Walker, Taylor
Galindo, Alejandra
Heshmaty, Bradley
McAdaragh, Jessica
Shen, Xinyu
Zhang, Zel
Traub, Matt
Colasurdo, Alexa
Yin, Kexin
Hoyme, Jayson
Bolohan, Ioan
Rue, Daniel
Richard, Meredith
Blumberg, Morgan
Lubarsky, Adriel
Watson, TaJuan
Brown, Ansley
Archer, Jordan
Bruder, Evan
Lewis, Kai
Duong, Van
Hunter, Joe
Batchelor, Katharine
Hamlett, Lauren
Goettel, Jeffrey
Chu, Phillip
Nasim, Walid
Sieloff, Anna
Hoang, Bryan
Spelman, Phillip
Baldock, Joe
Stark, Anderson
Valenstein, David
Pryor, David
Polisetti, Satya
Cheng, Christina
Goel, Nitin
Viswanath, Naintara
Haidary, Zakeria 
Engels, Collin
Oddo, Laura
Hill, Katherine
Stewart, Amanda
Hunt, Graham
Heyward, William
Vess, Dillon
Su, David
Gagliardi, April
Neenan, Luke
Newton, Daniel
Scroggins, Haley
Segovia, Luis
Bola-Oyeledun, Morad
Credle, Grant
Finkelstein, Marshall
Brinker, Smith
Blaney, Bre
Hieronymus, Beth
Stiegler, Doug
Manning, Trey
Biehl, Alexander
Foster, Emily
Freudenthal, Scott
Gondha, Shyam
Jones, Sydney
Liu, Emily
Kelly, Matthew
Vicario, Jillian
Mohajerani, Sophie
DeSio, Vincent
Lynch, Brittan
Melvin, Michael
Taylor, Andrew
Cassidy, Patrick
Nerkowski, Jessie
Li, Lisa
Evans, Lillian
Cherry, Forrest
Martinez, Kathryn
Avara, Jaclyn
Hunter, Hayley
MacDevette, Kelly 
O'Connell, Lauren
Patton, Charles
Ransenberg, Alexander
Stutesman, Jack
Thompson, Amanda
Keith, Alexander
Henson, Derek
Reynolds, Imani
clemente, Michi
MacGregor, Michael
Sun, Chang
Blaser, Eric
O'Drobinak, Katie
Starkey, Stetson
Egbuna, Toby
Palmer, Lea
Hubbard, Ashley
Giannuzzi, Andrew
Patel , Neal
Glady, Moriah
Bard, Harrison
Cross, Johnny
Tiano, Jamie
Meusel, Jocelyn
Swaim, David
Henshall, Roxanne
Warren, Jordan
Dwyer, Shannon
Lumbra, Evan
Shisler, Grant
Lee, Yan Ling
Baratam, Prasant
Casazza, Zack
Peck, Haley
Shaw, Katie
Skill, Kristen
White, Madelyn
Shah, Kush
Tambellini, Jonathan
Wetherby, Benjamin
Jacob, Hailey
Yen, Sharona
Neveleff, Julie
Staub, Nathan
Malarkey, Christine
Vasa, Rashmitha
Trocinski, Ryan
Daly, Connor
Smith, Tyler 
Ilario, Nick
Peat, Alex
Harrison, Bryan
de Lannoy, Cyara
Forbes, Jeff
Gupta, Tarun
Lilley, Paul
Huelster, Max
Hodge, Jordyn
Everhart , Sarah
Garval, Stefan
Guerrazzi, Andrew
Duncan, Kalil
Gentry, Emma
Sigarto, Andrew
Chiu, Andy
Vakil, Mansi
Soernssen, Peyton
Patel, Jaimin
Riccio, Mike
Wagaman, Katherine
Barach, Jake
Vos, Olivia
Brozowski, Carrie
Gibbons, Collin
Posas, Erin
White , Bailey 
Purdy, Erin
Schmitz, Drew
Craig, Ben
Stewart, John
Clapper, Courtney
Ramsey, John
Stowe, Andrew
Lowery, Patrick
Schwartz, Jon
Harrison, Jack
Jackson, Austin
Gilbert, Brandon
Allison, Collins
Kubitschek, Kenneth
Brown, Zak
Mahrer, Jonah
Neuenfeldt, Paige
Angara, Anurag
Dlamini, Zakhele
Fang, Danni
Polvino, Jenn
Zhao, Jeanie
Alinaghi, Mateen
Garner, Brian
Mace, Dashiell
McKinney, Jake
Mueller, Will
Sasser, Holden
Vallecillo, Cindy
Harry, Camille
Montgomery, Natanya
Evert, Harrison
Mehrbakhsh, Amir
Aguilera, Juan
Stohlman, Tyler
Egan, Charlie
Smetana, Beth
Chen, Peter
Shaw, Avery
Vance, Will
Duvall, Carly
Clark, Nathan
Hu, John
Voler, Isabelle
Watson, Alex
Helms, Austin
Cheng, Haoshi
Lee, Ryan
Thompson, Tyler
Coale, Chase
Swope, Melissa
Hastings, Cort
Hare, Rachel
Marcantonio, Cassie
Van Wingerden, Eric
Vittert, Sammi
Donaldson, Christopher
Lucido, Joseph
Aboujaoude, Rita
Medlin, Paige
Favorite, Emily
Li, Li
Messerly, Blake
Pierce, Fields
Pena, Mike
Jones, Chris
McClendon, John
Baldridge, Anne Burke
Gliddon, Spencer
Whitmeyer, Allison
Patrick, Wells
Lovejoy, Matthew
Wright, Dylan
Tan, Kristina
Goldin, Patrick
Braxton, Tyler
Sohmer, Evan
Sowinski, Brian
Wei, Yaner
Thomas, Maddy
Bales, Alex
Han, Joseph
Boddie, Olivia
Wiener, Alexis
Dingler, Amy
Latimer, Hunter
Mullendore, Julia
Surampudy, Gaurav
Holder, Michael
Zartman, Paige
Gores, Andrew
Field, Mary Kathryn
Bosco, Tanner
Curnes, Natalie
Miller, Richard
Kennedy, Sean
Boyle, Lexi
Norris , Brianna 
Fedder, Victoria
Fogel, Tera
Davidson, Alsey
Arditti, Alex
Davis, Russell
Zeigler, Maddie
Dworschak, Daniella
Sonderegger, Nicole
Morrissett, Will
Petosa, Joe
Prime, Theo
Rosenberg, Dylan
Rand, Jackson
Skavroneck, Joey
Leoni, Michael
Chung, Ethan
Ratra, Shiamak
Almquist, Alex
Kazi, Basil
Strassman, Jamie
Porter, Simon
Bigelow, Matt
Stimple, Jack
Ott, Gage
Dietz, Austin
Evans, Karissa
Baldwin, Jacob
Grant, Ben
Lachgar, Nabil
Williams, Matthew
Winston, Tracy
Cruse, Trell
Halim, Mason
Hollowell, Caitlyn
Zhang, Li
Silva, Frank
Kazlouskaya, Natallia
Gil, Lauren
Kelley, Ryan
Grillo, Austin
Snodgrass, Alex
Bridges, Elwyn
Clare, Dain
DeBartolo, Joe
Young, Will
Oliver, David
Schwartz, Matthew
McClung, Sean
Bai, Brianna
Piscitelli, Paul
Henderson, Sam
Edwards, Marisa 
Stanley, Hannah
Johnson, Cole
Battle, Jefff
Edmiston, Robbie
Liu, Stephen
Dombrowski, Lauren
Albert, Sam
Dakoriya, Vivek
Minore, Rachel
Xie, Sarah
Zhu, Jesse
Isemann, John
Watts, Stephanie
Ryan, Sean
O'Neill, Patrick
Deal, Marshall
Allison, -
Ragsdale, TJ
Lin, Ying
DeLong, Jen
Walters, Grey
Wilson, John
Cronson, Deena
Kalmbach, Brittany
Kenan, Taylor
McDonald, Wes
Rankins, Michaela
Dibble, Ian
Bereche, Tara
Farmer, John
Shim, Mimi
Vavolizza, Mark
Wilhelm, Alex
Baker, Ty
Schafer, Paige
Jenkins, Gage
Purcell, Grant
Bethune, Mel
Feeley, Jessie
Roseborough, Jordan 
Toloui, Hannah
Wagner, Elly
Busby, Grace
WIlliams, Drayton
Onigbinde, Theo
Shannon, Conor
George, Rachael
Plotnikov, Andre
Butler, Courtney
Smith, Mason
Yechoor, Vamsi
Kim, Jeff
Radatovich, Brendan
Riess, Patrick
Duchardt, Hannah
Fox, Peter
Shook, Mattie
Flinn, John
Pincus, Jacob
Fuqua, Martha Stewart
Jacobson, Briana
Folan, McKenzie
Reckford, Alexander
Paredes, Daniela
Haber, Alec
Adler, David
Barnhart, Madison
Ellington, Scott
Yang, Andy 
Redmond, Devin
Comstock, Brent
Hardies, Jill
Kass, Bradley
Dawson, Hunter
Beckman, Lee
Gopman Slonim, Michael
Gopman Slonim, Michael
Somers, Jackson
Ellis, Matthew
Nuccio, Katie
Moore, Chase
Robertson, George 
Van Den Eynde, Mitch
Johnson, Kubi
Snelling, Jack
Steppe , Connor 
Beals, Josh
Waters, Andrew
Fowler, Tracie
Hausfeld, Graham
Lane, Sam
Blair, Zoe
Campos, Ingre
Maltrotti, Nicole
Miller, Anna
Ehlers, George
Homer, Sierra
Schaberg, Andrew
Farrell, Christina
Barton, Mike
Zhou, Candice
Hafiz, Ishrat
Kramer, Megan
Lee, Alex
Mirabedini Jaramillo, Susie
Storey, Katelyn
Finkelstein, Justin
MacCormac, Deanna
Kickham-Dawes, Lydia
McCartney, Alex
Perkins, Baxter
Eichenberger, Daniel
Euceda, Genesis
Peterkin, Jordan
Schrager, Sonia
Alowonle, RJ
Caragher, Mike
Hagan, Tyler
Henriques, Will
Kowalski, Sarah
Alowonle Jr., RJ
Manweiler, Katherine
Orenstein, Elliot
Brody, Pam
Brown, Zach
Liu, Garbo
Gurkin, Matt
O'Malley, Ryan
Patel, Sagar
Jones, Holly
Hamed, Harris
Hayward, Joshua
Haines, Connor
Lewis, Michael
Rowe, Cassidy
Lieberman, Asa
Gregoire, Emily
Harris, Gabriel
Hayes, Conor
Ratliff, Millie
Balbirnie, Sean
Bonthu, Suhas
Grad, Katie
Hansen, Stephen
Lu, Ye
Maltsev, Dan
Ng, Annie
Shiro, Alexis
Gonzalez Sanchez, Karina
Meyer, Hays
Schrum, Chris
Russo, Michael
Paley, Jack
Brecher, Casey
Ouyang, Luman
Murray, Merritt
Dinkins, Elizabeth
Miller, Jaymee
Coe, Bob
Urbano, Jason
Gregor, Nick
Schultz, Andrew
Tuggle, Mary
Thomason, Kendall
Alahari, Sam
Tocheva, Rally
Wadsworth, Graham
Kenna, Peter
Chen, Anita
Moore, Elizabeth
Park, Yunah
Urquhart, Wes
Conery, Karlyn
Connolly, Grace
Deepee, Steven
Breve Mazzoni, Alec
Larson, Nick
Rutherford, Dayton
Smith, Oliver
Orringer, Kayla
Steinkamp, Ted
Mejia, Alejandro
Sankar, Visruti
Sundaram, Karthik
Muoio, Mike
Osteen, Anne Bennett
Pergande, Morgan
Alford, Ali
Arnav Prieto, Mauricio
Smith, Brian
Heller, Anna Kate
Silk, Michael
Su, Corey
Long, Stephen
Wilson, Sterling
Fuller, Cole
Gay, Abigail
Smith, Austin
Kirchner, Michael
Miller, Luke
Zwart, Elizabeth
Barnes, Jimbo
Pottle, Annie Kate
Upton, Liza
Pritts, Alex
Rowe, Blaire
Glorio, Tom
Moen, Leslie
Acuff, Bo
Scheffer, Annie
Davis, Alexis
Williams, Emma
Hulsey, Caty
Matthews, Charlotte
Campbell, Adam
Drysdale, Caroline
Poulimenos, Vickie
Chung, Kristen
Leone, Griffin
Werk, Caroline
Madaffari, Chris
Temple, Nick
Olentine, Matt
Jin, Jennifer
Reaves, Chelsea
Crenshaw, Elizabeth
Berger, Tyler
Polisetti, Nishant
Lozada , Vince
Harris, Jordan
Patel, Sagar
Paulsen, Eric
Lynch, Conor
Lucht, Becca
Hawkins, Ian
Merendino, Katelyn
Hunt, Richard
Nicholson, Dalton
Patel, Hinal
Dunleavy, Lisa
Landry, Ashley
Papetti, Nicole
Bari, Zeshan
Shoemaker, Adam
Hemmer, Catherine
Marley, Amanda
Bowman, Anthony
Senior, Bret
Dawson, Council
Brooks, Sarah
Saad, Mahmoud
Bui, Stephanie
McCauley, Charlotte
Gao, Julie
Moloney, Patrick
Zheng, Yongwei
Cacciatore, Mike
Amasya, Craig
Arneson, Mike
Hedadji, Mohammed
Shackelford, Grace
Tirpak, Tyler
Nix, Preston
Burke, Graham
Merendino, Katelyn
Saxena, Nisha
Rizzo, Mark
Bregier, Josh
Hammond, Rachel
Rummell, Harry
Klawinski, Peyton
Byrd, Don
Merrill, Hamilton
Duma, Matt
Haidinger, Alec
Burns, Kyle
Egan, Chas
Foster, Drew
Kerker, Sami
Rhine, Michael
Tompkins, Parks
Wiener, Jill
Kennihan, Katie
Davenport, Allie
Hayes, Michelle
holberton, brian
Milanese, Kimmy
Fisher, Zoe
Hawk, Nick
Meyer, Paul
Simmons, Brooks
Ferrall, Jessica
Shapiro, Adam
Schwab, Rachel
Cady, Max
Brown, Landry
Aldridge, Creighton
Barnaba, Maddie
Doetzer, Ben
Foulks, Tyler
Johnson, Emily
Orleans, Leigh
Shockley, Tre
Smitherman, Rachel
Friedman, Jordana
Gasior, Madeline
Jahn, Patrick
Schneider, Kate
Hoffmann, Jessica
Cohen, Allie
Carpenter, Charlie
Ball, Nick
Popivchak, Courtney
Gutekunst, Luke
Hussey, JP
Hanna, Andrew
Tonnesen, Tyler
Cooke, Connor
Schmidt, TJ
Baudhuin, Kimberly
Kabra, Jay
Ririe, Caroline
Romano, Isabel
Krupa, Al
Garg, Isha
Barlow, Ryan
Chandak, Resha
Dove, Emily
Thompson, Shannon
Trenkova, Irina
Hall, Alison
DiRuzza, Alec
Pasi, Alisha
Lerner, Jake
Muriuki, Ian
Lee, Jessica
Talcott, Charlie
Strickland, Julianne
Parks, Daniel
Sclafani, Matt
Espinoza, marvin
Rento, Alex
Graham, Riley
Collier, John
Goldstein, Elianna
Eatherly, Rickie
Johnson, Chris
Bilgi, Ankit
Denenberg, Rachel
Harris, Maelin
Holmes, Stephen
Wagaman, Lauren
Kothari, Neha
Young, Rob
Clary, Drew
Clayton, Jack
Doolen, Sarah
Freeland, Meredith
Li, Richard
Zheng, Steven
Zwierzynski, Jason
James, Johnny
Brittain, Tanner
Taylor, Caleb
Corder, Jarrett
Best, Ryder
Green, Chloe
Chen, Kuanfu
Rymiszewski, Erin
Wheeler, Jenny
Morrel, Luke
Kutz, Erin
Cuppett, David
Taylor, Anna
Spalding, Mandy
Janicello, Zeke
Pontrelli, Madison
Occhiogrosso , Anthony 
Crist, Stefanos
Kalmbach, Rebecca
Wurmser, Lis
Clemmons, Mike
Pina, Yakel
Veazey, Pearce
Sirois, Juliana
Little, Katie
Swetlitz, Daniel
Nunn, Ryan
Zinna, Erik
Zechel, Anna
Bowser, Cole
Welsh, Brenna
Batchelor, Chris
Janeczko, Joe
Iyer, Sid
Catha, Taylor
Catha, Taylor
Banoczi, Alex
Arora, Radhika
Lobinsky, Courtney
Jasinski, CJ
Floyd, Leslie
Reddix, Anyssa
Porobic, Amila
Amiai, Micheline
Menon, Kavya
Shah, Richa
Gallant, Caitlin
Chu, Bryan
Delatte, Haley
Lo, Vincent
Thompson, Eric
White, Emma
Fang, Mengmeng
Hoke, Ashley
Dull, Katherine 
Akers, Travis
Chase, Lucy
Gaines, Allie
Pathak, Neil
Shell, Allie
Miller, Diego
Cremisi, Mia
Ramirez, John
Murphy, Maddie
Rippey, James
Douglas, Nelson
Howard, Stephen
Fuller, Anna
Rice, Morgan
Brannigan, Megan
Schroeder, Amanda
Kelly, Caroline
Remmel, Remington
Gonzalez Pena, Evie
Lachgar, Sami
Beal, Tasha
Albert, Ben
Watts, Thomas
Venkatraman, Sneha
Tai, Eric
Howard, Philip
Hermina, Lilly
Aunce, Joe
Riegel, Sophie
Blanchard, Maria
Gabianelli, John
Graddy, Wes
Lindvall, Henrik
Guess, Connor
Yevak, Caroline
Schietinger, Grant
Whitty, Chrissy
Schomp, Rachel
FitzGibbons, Lauren
Chen, Katharine
Doby, Miller
Mehta, Shubhang
Wilson, Seth
Garwood, Anna
Garwood, Anna
Sturms, Stephanie
Lee, Anne
Smith, Graham
Oldenburg, Peyton
Murphy, Peter
Evans, Will
Burt, Bailey
Bell, Mary Grady 
Stidham, Luke
Miller, Sarah
Emrick, Keegan
Apple, Maggie
Cunningham, Jordan
Ding, Ronald
Guo, Mike
Mozingo, Evan
Fraley, Danielle
Miner, Sam
October, David
Yoo, Sam
Peikes, Ethan
Escourse, Kelsey
Lim, Allie
Rich, Sara
Hornor, McKee
Cartrette, Elizabeth
Friedman, Jacob
Lowery, Mary Scott
Pevonka, Caroline
Ciocca, Luke
Macri, Ryan
Singla, Arnav
Verma, Roshni
Jambhekar, Sidd
Sloan, David
Zasacky, Tye
DiMaggio, Dante
Bard, Ali
Dokell, Bella
De La Vega, Rafaella
Siegal, Ian
Aronson, Kayla
Wellen, Catherine
Ballew, Josie
Raghunandan, Shannon
Lindemanis, Richard
Young, Jenny
Mace, Emily
Quigley, Christina
Mainous, Liz
Skinner, Andrew
Narag, Paolo
Mendoza, Elena
Goodnight, Anna
Lee, Alexandra
Deng, Chuck
Gilchrist, Cameron
Singh, Sabrina
Mitchener, Larson
Hufham, Katy
Blaya, Ryan
Patterson, Connor
Patterson, Connor
Carroll, Logan
Bortey, Cyrous
Fern, Ali
Hagenburg, Justin
Smith, Susannah
Sarnoff, Jared
Shearin, Holden
Lilley, Sam
Fischer, Jack
Lo, Andrea
Byron, Nic
Krachenfels, Nico
Calikoglu, Murat
Karakrah, Hanadi
Farfan, Daniel
Howard, Erik
Verma, Vishesh
Batra, Neha
Cooper, D'Shaun
Kovach, Ben
Berry, Elizabeth
Good, Ethan
Daly, Lauren
Darden, Thomas
Shivdasani, Nick
Lin, Alexis
Harden, Kendall
Trupiano, Nikki
Russell, Colin
Lee, Kristen
McKinley, Patrick
Godwin, Emily
Larabee, Landon
Caison, Kirkland
Boyd, Ben
Toma, Nick
Bradley, Keri
Felker, Larkin
Prospero, Niko
Richardson, Erica
Silk, Ryan
Story, Austin
Wydra, Ryan
Singh, Navi
Economos, Marika
Fronc, Julia
Kronstedt, Brielle
Lee, Allison
Morra, Anthony
Magee, Zander
Magee, Zander
Andrews, Parker
Ball, Nicholas
Garcia, Erica
Alpern, Evan
Chaffin, Aisling
Taflinger, Alyssa
Wagner, Caroline
Murphy, Isabella
Lee, Andrew
Chen, Haokun
Brooks, Dylan
Xu, Jason
Trowers, None
Gideon, Rachel
Beltrani, Alexa
Zhou, Jessi
Dockery, James
Kelly, Tyler
Son, Julie
Katz, Sam
Mills, Nicholas
Pipaliya, Ronak
Zeitouni, David
Niersbach, Carolyn
Savino, Allie
Snyder, Max
Mack, Andi
Cooper, Jessica
Korf, Rachel
Berkowitz, Jordan
Boone, Michael
Yardley, Joe
Harer, Aoife
Lerner, Nathaniel
Ortiz, Christian
Landerer, Harold
Gronmeyer, Samantha
Wickham, Edward
Von Steen, Connor
Runkle, Daniel
Lane, Kevin
Mueller, Abby
Rhymer, Caroline
Collins, Devin
Plunkett, Austin
Sanchez, Karla
Krantz, Michael
Miller, Michael
Gilligan, Frank
Wei, Ashlyn
Condrey, Kylin
Addai, Maya
Schmidt, Jacob
Bravante, Matthew
Torrieri, Giovanna
Duarte, Pedro
Walzel, Benjamin
Mareno, Jordan
Owens, Phillippa / Phil
Jarrell, Rob
Berkowitz, Brandon
Baloch, Hamza
Berkenblit, Brett
Chang, Andrew
Baloch, Hamza
Emery, Maggie
Wiggins, Lindsey
Liao, Ziyu
Queen, Amy
Graves, Alex
Albright, Stephen
Hall, Grant
Jonathan, Dani
Ortiz, Becca
Newhouse, Katie
Asgari, Yashar
Olofson, Zack
Upton, Eryn
White, McKenna
Link, Colleen
Ma, Ryan
Jones, Harper Rae
Nelson, Aubri
Breck, William
Cox, Eliza
Drees, Trish
Filippone-Hozdevila, Callen
Brennan, Anna
Onderdonk, John
Samarakoon, Sam
Johnson, Regan
Carter, Hinton
Jackson, Will
DiPietrantonio, Lucas
Martin, Marshall
Hodge, Kylie
Kastner Rosenqvist, Andrea
Millar, Ben
Schmitz, Jess
Creissen, James
Meyers, Ted
Devine, Marissa
Shaqiran, Betty
Lee, Alex
Patel, Drushti
Witmer, Sarah
Carp, Ryan
Patel, Drushti
Ullrich, Tinsley
Barnett, Travis
Illies, Brendan
Fussell, Kevin
Davis, Blake
Braccia, Ally
Fang, Ziwei
Bodea, Alan
Wright, Kathryn
Selnes, Alec
Haverty, Cole
Stevens, Nicho
Agarwal, Divya
Zhang, Yusheng
Gwynn, Megan
Piasecki, Phil
Morrison, Jane
Stompel, Lizzy
Hazerjian, Zoe
Garrelick, Matt
Noble, Jared
Smith, Parker
Beasley Jr, Keith
Harty, Mackenzie
Alpern, Austin
Sykes, Austin
Monson, Stenn
Seng, Barry
Farooqui, Zareen
Penland, Christina
McMillan, Jeremy
Vtorov, Alec
Moss, Parker
Young, Garret
Holland, Chris
Conley, Amanda
Yeargan, Fisher
Pothireddy, Navya
Diao, Laurence
Willis, Brinson
Lopez, George
Kedia, Vibhor
McNeil, Kelly
Ye, Vanessa
Hamil, Forrest
Hartigan, Alexis
Tanous, Sky
Taub, Alex
Wittman, Parker
Atluri, Sreya
Gibbons, Clare
Lal, Mangza
Pasteris, Lindsay
Garcia, Marek
Hallett, Campbell
Vo, Jennie
Vo, Jennie
McMullen, Daniel
Chappell, Scott
Carrington, Kate
Cochrane, Robert
Hunt, Tyler
Pruitt, Matthew
Bush, Jamie
Strebel, Sarah
Paddison, Jack
Sapyta, Will
Senior, Ben
Henderson, Diamonde
Richter, Bobby
Lloyd, Keegan
Budd, Mac
Shell, Stanford
Lockwood, Eli
Nunez del Arco, Lino
Sellers, Austin
Bell, Michael
Bhatia, Anish
Bettadapur, Sachin
Freeman, Reagan
Nathan, Michael
Medlock, Taylor
Dunbar, Will
Grill, Carson
Barondes, Dan
Kennedy, Katie
Allen, Bennett
Aggarwal, Harry
Huang, Jesse
Peters, Missy
Kisiluk, Natasha
Keener, Jessie
Houk, Davis
Cabana, Laura
Schwartz, Dean
Crema, Maddy
King, Andrew
Ridley, Nicole
Amesur, Varun
Hawley, Andrea
Scott, Ryan
Scott, Ryan
Mehta, Poojan
Schellpfeffer, Austin
Phillips, Mia
Comsia, Alex
Anglum, Andrew
Eckmann, Sebastian
Scalise, James
Littlejohn, Patrick
Amoroso, Jack
Andrews, Kent
Safi, Sara
Saslow, Everett
Paul, Naveen
Dunn, Olivia
Shelley, Sam
Farrell, Shannon
Kodali, Meghana
Lawton, Ryan
Sontag, Maggie
Hutchings, Khari
Li, Jennifer
Roberts, Peyton
Monroe, Josh
Melin, Katie
Udell, Alex
Voychuk, David
Asare, Victoria
Birney, Nick
Bilden, Thomas
Drewery, Michael
Meliones, Demetrios
Petersen, Thor
Stroud, Wes
Sikka, G
Murray, Addie
Murad, Brooke
Stancill, Samantha
Nguyen, Rebecca
Burns, David
Martin, Eliot
Herron, Josh
Ball, William
Ludwig, Austin
Davis, Tim
Milic, Ched
Myers, Trent
Spove, Anna
Sullivan, Michelle
Murphy, Mark
Williams, Basil
Prachith, Lucky
Wallen, Irene
Sawh, Michael
Barone, Kenny
McClellan, Ruby
Pyne, Britton
Dawson, Caroline
Madriz, Javier
Voelkel, McLean
Abdou, Zach
Khanna, Adhish
Boyden, Bo
Hong, Jason
Grotheer, Rachel
Keane, Elena
Patel, Asha
Baker, Shannon
Zoutewelle, Shep
Gardner, Tristan
Patel, Valmik
Manning, MacKinsey
Gogal, Adam
Dooley, Caroline
Parent, Austin
Fedder, Matt
Blackburn, Emily
Schwartz, Quintin
Bravo, Danny
Bach, Madeline
Martensen, Trent
Sjoberg, Polly
Evans, Leila
Barron, Olivia
Lucas, Hardin
Sozio, Ben
Leiton, Raxel
Pupi, Vince
Wilkins, Olivia
Smith, Trevor
Cox, Ethan
Flye, John
Pate, Caroline
Donlin, Meg
Pickens, Kevin
Terzic, Leila
Trentini, John
Michaux, Savanna
Bell, Geoff
Aguilar-Diaz, Yasmin
Ding, Jessica
Conaway, David
Mao, Wendy
Patton, Claudia
Ochoa, Emilio
Kerestes, Brendan
White, Elliott
Cochrane, Maggie
Morrow, Nick
McDonald, Henry
Beller, Spencer
Meyer, Marielle
Yang, Michael
Hawks, Lexi
Darch, Kim
Yakaboski, Kaitlyn
Mangin, Jack
Lee, Erika
Jarrett, Mason
Lesha, Lauren
Mckee, Jasmine
Trechsel, Tristan
Bourdeaux, Mimi
Sheridan, Hunter
Smith, Luke
Gronmeyer, Samantha
Vilim, Carter
Sardinia, Michael
Won, Lance
Bini, Cailin
Clinton, Emily
Harrison, Ladd
Batchelder, Teddy
Kabrich, Jack
Busby, Griffin
Charles, Bri
Sheffield, Richard
Su, Qi
Rodriguez, Kevin
Bonatz, Maggie
Malik, Ravi
Maxwell, Andrew
Godfrey, Frank
Williams, Barton
London, Jared
Atkinson, Robert
Kenny, Ian
Arnold, Emily
Mccain, Kristen
Kirkman, Sam
Wong, David
Malisetty, Neehath
Bradbury, Baxter
Vickers, Chelsea
Carvajal, Ines
Kozareva, Fania
Passaly, Erin
Hernandez, Bryan
Estroff, Jamie
Beale, Ryan
mith, Hannah
Staker, Abby
Gowland, Charley
Winiecki, Allie
Khazzaka, John
Anandani, Soha
Pace, Carter
Smith, JoLynn
Wickham, Ashby
Moody, Claire
Luo, Daniel
Noble, Jack
Gandhi, Priya
Naik, Vishal
Stockton, Elizabeth
Ocano, Mariana
Thakur, Kunal
Mahalingam, Tanisa
Copeland, Marissa
Hoyt, Lindsay
Sykes, Jonathan
Robertson, Jack
Arora, Nikhil
Kloster, Katie
Randall, Jake
Riley, Owen
Frelich, Jacob
Gingrich, Jarrett
Schepperley, Megan
Mckane, Kent
Ullrich, Annie
Jenkins, Eugenia
Currie, Kayleigh
Balthazar, Ben
Patel, Darshan
Chandnani, Armaan
Perry, Jackson
Guin, Bryan
Strickland, Graeme
Brown, Victor
Panchavati, Sravya
Carsanaro, Scott
Pal, Aashi
Pollack, Tyler
Wu, Bianca
Szogas, Natalie
Ritger, Elizabeth
Brindis, Jasper
Schoenwald, Brock
Canney, Sam
Sefler, Julia
Paiano, Natalie
Ayscue, Katie
Finn, Liam
Wyatt, Camille
Liauw, Evangeline
Robinson, Victor
Herron, Ryan
Coody, Christian
Godin, Nathan
Gladd, Caroline
Sullivan, Bridgette
Hall, Owen
Boggis, Tommy
Cruzat, Marianne
Sawhney, Rabina
Love, Mike
Oelbaum, Jason
Sadani, Yash
Okraski, Trish
Jane, Marcel
Whitman, Byers
Jain, Sahil
Jones, Taylor
Guenther, Feline
Gomez, Nico
Attala, Nick
Patel, Akshay
Pruitt, Sydney
Murray, Madeline
Linton, Kent
Michie, Kyle
Palmer, Ben
Ibrahim, Joseph
Gandhi, Arjun
Lopez Sotillo, Alfred
Slowin, Austin
Chellani, Kris
Apple, Alex
Passaro, Caitlin
Divietro, Marisa
Savage, Jeyla
Cassidy, Sasha
Leinbach, Griffin
Cobb, Austin
Walker, Michael
Malmstrom, Caroline
Hager, Elaine
Storey, Grace
Cox, Ashley
Morrison, Elise
Ramakrishnan, Sapna
Gillogly, Trevor
Swierkowski, Rebecca
Rivera, Kaeli
Tucker, TJ
Lyons, Patrick
Mann, Katie
Eskender, Nathan
Smith, Josh
Dean, Michael
Burick, Jordan
Robertson, Tyler
Sullivan, Trey
Firrincieli, David
Lewis, Emilie
Ix, Sebastian
Allen, Matthew
Kelley, Anna Grace
Farrell, Lorcan
Kenna, Kevin
Bell, Albert
Peeples, Connor
Jones, Kennady
Berry, Phillip
Krupa, Michael
Pollone, Jonah
Baxter, Jeff
Allison, Emily
Piehler, John
Burns, Peyton
Whyte, Kat
Cregan, Riley
Abbott, Breanne
Boswell, Olivia
Covington, Sawyer
Huffines, Bea
Pittman, Emily
Wishnek, Jacob
Lee, Emma
Bhatia, Dhvani
Baslious, Jeremy
Mintzias, Corina
Chen, Wei Chee
Conway, Shawen
Mussack, Monica
Cairns, Noah
Hargraves, Luke
Klee, Brandon
D'Persaud, Andrew
Moody, John
Serafen, Elizabeth
Verdi, Emma
Fanning-Haag, Cole
Ghanem, Tad
Oberto, Corey
Curran, Jesse
Brighton, Micah
Villacis, Annie
Blackard, Will
Cheung, Mimi
Graham Nihmey, Jordan
Bono, Michael
Summers, George
Nguyen, Michael
de Waal, Anja
Sharma, Rosh
Zinner, Mattison
Wu, Tony
Atieh, Ahmad
Meise, Ashley
Leland, Mary McCall
Patete, Annalise
Tecle, Senay
Teems, Megan
Siddiqui, Salihah
Young, Caroline
Estes, Hannah
Yusuf, Baaqir
Fischler, Daniel
Beiger, Katie
Tambe, Kunaal
Brown, Spencer
Flowers, Emily
Dempsey, Annie
Weeks, Anderson
Moody, Jack
Mehlman, Ross
Sewell, Jack
Lewis, Connor
D'Souza, Mabel
Lyons, Matthew
Rudd, Hollis
Shah, Mihir
Jordahl, Erin
Dixon, Badham
Amico, Evan
Dunderdale, Abe
Luter, Stuart
Osiecki, Cameron
Mehta, Raul
Shorkey, Ryan
Gerlach, Laura
Gundlach, Christian
Vankayala, Vaishnavi
Lakhany, Zain
Brown, Ben
Hughes, Holleman
Putnam, Cameron
Murphy, Alexandra
Harris, Welles
Li, Rebecca
Sleeper, Jack
Lassiter, Everette
Cervi, Nicole
Brechnitz, Greta
Walters, Carter
Groenhout, Thomas
Jessup, Carter
Toney, Lauren
Gray, Lexi
Kolk, Caroline
Gomez, Michelle
Tan, Marcus
Sylvester, John Hayden
Young, Brendan
Cairns , Adelaide
Lynch, Alexis
Curme, Lillian
Ziperski, Laura
Koch, Denisse
Rocco, Logan
Jenkins, Alex
Burch, Jon
Stoneking, Owen
Surana, Khushi
D'Ambrosio, Jake
Hashe, Cayla
Hanby, Mackenzie
Schinsky, Matt
Parikh, Vedika
Foster, Kate
Franco, Anthony
Cohen, Dany
Foster, Shannan
Woodard, Reagan
Cuevas, Bryan
Aleman Galano, Jose
McLaughlin , Matt
Hutto, David
Blackwelder, Jakob
Shepard-Moore, Michael 
Garcia, Meredith
Kobrin, Grant
Cross, Emmy
Borgese, Annabella
Gibbons, Michael
Fornatoro, Brian
Cantu, Francisco
Jain, Meet
Helms, Alex
LaMasse, Jessie
Dietzman, Logan
Welch, Nicole
Bowen, Danny
Tanjuatco, Trey
Damiano, Alex
Ozello, Jackson
Lutz, Charlotte
Macdonald, Reed
Wilder, Katie
Ikiz, Oz
Ham, Colin
Kum, Sonio 
Spence, Jacob
Anand, Riya
English, Mason
Parker, Josh
Grossman, Alton
Glontz, Elizabeth
Sibley, Brendan
Speakman, Maddie
Black, Jenine
DeBord, Taylor
Smith, Catherine
Howard, Liz
Goodson, Grey
Sherman, Baez
Jamrog, Chris
Foreman, Shelby
Forero, Andres
Washburn, Zach
Brennan, Danny
Jones, Cameron
Zheng, Jeff
Zezzo, Madison
Haig, Markus
Zeng, Cecilia
Johnson, Calia
Johnson, Aston
Long, Kathryn
Parker, Abby
First, Angie
Bouslov, Gabe
Thomas, Stephanie
Kuang, Joanna
Moore, Kirstie
Oliveira, Gabe
Boinapally, Dhruv
Mohamed, Abdel
Graham, Lauren
Bendalin, Jacob
Staton, Dominique
Lewis, Adam
Mugisha, Fidele
Larkin, Lindsay 
Dimitriou, Dimitris
Seubert, Colton
Motley, Mary
Gomez, Angeles
Warren, Michael
Martin, Rachel
Billman, Nikita
Crum, Drew
Keller, Len
McFarland, Lindsey
Moneymaker , Lacey
Andreu Sanz, Bianca
Bower, Will
Richmond, Camaryn
Gowan, Elizabeth
Cox, Jordan
Kenan, Claire
Lanzas, Alec
Lloyd, William
Perez, Ben
Kleitches, Demi
Ralls, Ben
Stox, Tyler
Reiter, Allie
Benson, Harrison
May, Carolyn
Thomas, Reed
Sparks, Tia
Gobbi, Livia
Hyde, Alex
Landry, Pearce
Calton, Andrew
Ohmstede, John
Upchurch, Deanna
Nevant , Suzanne 
Alberse, Michael
Ni, Ana
Malhotra, Richa
Lowder, Mary Spain 
Mccraw, Brett
Whelchel, Isabel
DeGregorio, Eli
Stratton, Rachel
DePolo, James
Sugg, Catherine
Salice, Philip
Kapural, Daniella
Randhawa, Beshawn
Raets, Bram
Creatore, Maddie
Creatore, Maddie
Hardison, Ansley
Gornto, Lauren
Martin, Pryce
Miller, Nate
Ghafoor, safia
Dowler , Austin
Raiola, Matt
Leonard, Mimi
Donofrio, Jake
Delgado, Cynthia
Pruss, Max
Sam, Eileen
Wynn, Hailey
Omeechevarria, Nico
Pake, Graham
Nguyen, Bryan
Dinges, Jack
Klaff, Lindsey
Limroth, Ronan
McGregor, Will
Searcy, Carter
Dikolli, Thomas
Witek, Bernard
DeMarco, Kaitlin
Morgan, Jake
Gardner, Will
Whelan, Mary Kate
Roach, Savannah
Chadwick, Alexandria
Marshall, Jasmine
Curtis, Zac
Kabra, Isha
Buttitta, Michael
Sabogal, Alyssa
Ascencio Turcios, Jordy
Singer-Freeman, Ari
He, Michelle
Falcon, Tommy
Suwanmanee, Jenny
McDonald, Natalie
Goodwin, Ryan
Smith, Justin
Mangalindan, n/a
Valentino, Taryn
Bechter, Riley
Loren, Brett
deGolian, Katharine
Tran, Tu-Uyen
Ewell, Maddie
Craver, Reynolds
Munoz, Maddy
Greene, Sara Fran
Pavuluri, Archi
Sackstein, Jacob
McGuigan, Benjamin
Salib, Natalie
Zhang, Maggie
Tammi, Lexi
Martin, Amanda
Bell, Mackenzie
Gulati, Ashi
Akila, Hidy
Abou Sido, Khamees
Garvin, Caleb
Stone, Spener
Gonzalez, Isabella
Allison, Lindsey
Prego, Andrea
Pledger, Carson
de Larminat , Pauline
Walston, Temple
Credle, Anna
Krause, Eliza
Loughran, Courtney
Peveto, Emma
Arndt, Thomas
Scrudders, Owen
Durham, Elizabeth
Skahan, Jack
Spangler, Matthew
Mehta, Smit
Mast, Anabel
Florian, Liam
Davidson, Jack
Parker, Mary Grace
Clawson, Savannah
McClellan, Madison
Sistare, Luke
Morgan, Grant
Carry, Ben
Culp, Christian
Hansen, Sydney
Richards, Alden
Baddour , Henry
Cole, Emma
Soto, Felipe
Snyder, Teddy
Russell, Hannah
Sa, Grace
Good, Caitlyn
Oldham, Chris
Cowan, Jason
Vallapalli, Sujay
Kanumilli, Raj
Ruffolo, Robby
Tchebetchou , Sorelle 
Zhang, Jen
Vinson, Sidney
Nonez, Xavier
Tyson, Hayle
Regmi, Ujesh
Dou, Rachel
Dou, Rachel
Kantesaria, Ravin
Baghel, Arth
Gingrich, Brady
Hayes, Alexis
Romano, Cara
Garner, Jake
Fan, Daniel
Schuster, John
Canipe, John
Norona, Jordan
DeMaine, Connor
Leary, Michael
Batchelder, Will
Tanniru, Vamsi
Wacaser, Brandon
Markson, Emma"""

    remove_duplicate_lines_to_file(sample_input, "clean_names.txt")
